package com.example.memoryapp.game

import com.example.memoryapp.R

val cardsArray = arrayOf(
    R.drawable.clubs_7,
    R.drawable.spades_5,
    R.drawable.clubs_3,
    R.drawable.diamonds_7,
    R.drawable.diamonds_5,
    R.drawable.clubs_4,
    R.drawable.hearts_5,
    R.drawable.clubs_jack,
    R.drawable.clubs_ace,
    R.drawable.clubs_9,
    R.drawable.clubs_8,
    R.drawable.hearts_queen,
    R.drawable.diamonds_king,
    R.drawable.spades_2,
    R.drawable.hearts_king,
    R.drawable.spades_6,
    R.drawable.diamonds_9,
    R.drawable.spades_7,
    R.drawable.spades_king,
    R.drawable.spades_9,
    R.drawable.clubs_5,
    R.drawable.spades_ace,
    R.drawable.hearts_10,
    R.drawable.diamonds_ace,
    R.drawable.diamonds_3,
    R.drawable.black_joker,
    R.drawable.spades_10,
    R.drawable.hearts_2,
    R.drawable.spades_jack,
    R.drawable.clubs_2,
    R.drawable.spades_queen,
    R.drawable.diamonds_2,
    R.drawable.hearts_9,
    R.drawable.hearts_ace,
    R.drawable.diamonds_6,
    R.drawable.spades_3,
    R.drawable.hearts_3,
    R.drawable.diamonds_queen,
    R.drawable.diamonds_4,
    R.drawable.clubs_6,
    R.drawable.diamonds_10,
    R.drawable.clubs_10,
    R.drawable.hearts_jack,
    R.drawable.spades_8,
    R.drawable.hearts_4,
    R.drawable.spades_4,
    R.drawable.hearts_8,
    R.drawable.hearts_7,
    R.drawable.red_joker,
    R.drawable.clubs_king,
    R.drawable.clubs_queen,
    R.drawable.hearts_6,
    R.drawable.diamonds_8,
    R.drawable.diamonds_jack,)

val emojiArray = arrayOf(
//    R.drawable.emoji8,
    R.drawable.emoji1,
//    R.drawable.emoji12,
    R.drawable.emoji15,
//    R.drawable.emoji6,
//    R.drawable.emoji14,
//    R.drawable.emoji13,
//    R.drawable.emoji11,
//    R.drawable.emoji3,
//    R.drawable.emoji7,
//    R.drawable.emoji5,
//    R.drawable.emoji2,
//    R.drawable.emoji9,
//    R.drawable.emoji4,
//    R.drawable.emoji10,
    R.drawable.emoji16,)

val foodArray = arrayOf(R.drawable.milk,
    R.drawable.doughnut,
    R.drawable.juice,
    R.drawable.cocacola,
    R.drawable.icecream_1,
    R.drawable.pudding,
    R.drawable.beer,
    R.drawable.hotdog,
    R.drawable.coffee_1,
    R.drawable.icecream,
    R.drawable.toast,
    R.drawable.sandwich,
    R.drawable.sushi,
    R.drawable.drink,
    R.drawable.lollipop,
    R.drawable.coffee,)

val furnitureArray = arrayOf(R.drawable.frame10_2,
    R.drawable.frame9_3,
    R.drawable.frame12_2,
    R.drawable.frame12_1,
    R.drawable.frame9,
    R.drawable.frame10_1,
    R.drawable.frame11_2,
    R.drawable.frame10_3,
    R.drawable.frame9_1,
    R.drawable.frame11,
    R.drawable.frame9_2,
    R.drawable.frame12,
    R.drawable.frame11_3,
    R.drawable.frame11_1,
    R.drawable.frame12_3,
    R.drawable.frame10,)

val spaceArray = arrayOf(R.drawable.venus,
    R.drawable.ufo,
    R.drawable.solar_system,
    R.drawable.telescope,
    R.drawable.ursa_major,
    R.drawable.shooting_star,
    R.drawable.stars,
    R.drawable.satellite,
    R.drawable.saturn,
    R.drawable.rocket_ship,
    R.drawable.sun,
    R.drawable.uranus,
    R.drawable.space_capsule,)

val memoryArray = arrayOf(
    R.drawable.memory1,
    R.drawable.memory6,
    R.drawable.memory11,
    R.drawable.memory3,
    R.drawable.memory9,
    R.drawable.memory4,
    R.drawable.memory8,
    R.drawable.memory5,
    R.drawable.memory10,
    R.drawable.memory12,
    R.drawable.memory2,
    R.drawable.memory7,
)

val lightArray = arrayOf(
    R.drawable.light5,
    R.drawable.light9,
    R.drawable.light12,
    R.drawable.light6,
    R.drawable.light1,
    R.drawable.light8,
    R.drawable.light3,
    R.drawable.light11,
    R.drawable.light4,
    R.drawable.light2,
    R.drawable.light7,
    R.drawable.light10,
)

val rectangleArray = arrayOf(
    R.drawable.rectangle11,
    R.drawable.rectangle8,
    R.drawable.rectangle1,
    R.drawable.rectangle6,
    R.drawable.rectangle7,
    R.drawable.rectangle12,
    R.drawable.rectangle5,
    R.drawable.rectangle10,
    R.drawable.rectangle9,
    R.drawable.rectangle4,
    R.drawable.rectangle2,
    R.drawable.rectangle3,
)

val iconArray = arrayOf(
    R.drawable.icon6,
    R.drawable.icon11,
    R.drawable.icon12,
    R.drawable.icon1,
    R.drawable.icon3,
    R.drawable.icon8,
    R.drawable.icon5,
    R.drawable.icon2,
    R.drawable.icon7,
    R.drawable.icon10,
    R.drawable.icon4,
    R.drawable.icon9,
)

